[package]
name = "y2025"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
nom = "8.0"
rayon = "1.11"
tracing = "0.1"

[dev-dependencies]
rstest = "0.26.1"
tracing-test = "0.2.5"
